

name: Build and Publish


on: 
  push:
    tags:
      - "v*.*.*"


jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
      steps:
        - name: Prepare - Set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'microsoft'
            java-version: '11'
        - name: Prepare - Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Prepare - Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Prepare - Get Docker Meta
          id: meta
          uses: docker/metadata-action@v3
          with: 
            images: cc12703/wvp-gb28181-pro
            tags: type=match,pattern=v(.*),group=1

        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: |
            cd ./web_src
            npm install --registry=https://registry.npm.taobao.org 
            npm run build
            
            cd ../
            mvn clean package

        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ steps.meta.outputs.tags }}